// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: execution.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

type SwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	SizeUsd       float64                `protobuf:"fixed64,2,opt,name=size_usd,json=sizeUsd,proto3" json:"size_usd,omitempty"`
	Exchange      string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	IsSell        bool                   `protobuf:"varint,4,opt,name=is_sell,json=isSell,proto3" json:"is_sell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapRequest) Reset() {
	*x = SwapRequest{}
	mi := &file_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapRequest) ProtoMessage() {}

func (x *SwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapRequest.ProtoReflect.Descriptor instead.
func (*SwapRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

func (x *SwapRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *SwapRequest) GetSizeUsd() float64 {
	if x != nil {
		return x.SizeUsd
	}
	return 0
}

func (x *SwapRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *SwapRequest) GetIsSell() bool {
	if x != nil {
		return x.IsSell
	}
	return false
}

type DryRunResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EstimatedSlippage float64                `protobuf:"fixed64,1,opt,name=estimated_slippage,json=estimatedSlippage,proto3" json:"estimated_slippage,omitempty"`
	PriceImpact       float64                `protobuf:"fixed64,2,opt,name=price_impact,json=priceImpact,proto3" json:"price_impact,omitempty"`
	EstimatedOutput   float64                `protobuf:"fixed64,3,opt,name=estimated_output,json=estimatedOutput,proto3" json:"estimated_output,omitempty"`
	IsSafe            bool                   `protobuf:"varint,4,opt,name=is_safe,json=isSafe,proto3" json:"is_safe,omitempty"`
	RejectionReason   string                 `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DryRunResult) Reset() {
	*x = DryRunResult{}
	mi := &file_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DryRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunResult) ProtoMessage() {}

func (x *DryRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunResult.ProtoReflect.Descriptor instead.
func (*DryRunResult) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{2}
}

func (x *DryRunResult) GetEstimatedSlippage() float64 {
	if x != nil {
		return x.EstimatedSlippage
	}
	return 0
}

func (x *DryRunResult) GetPriceImpact() float64 {
	if x != nil {
		return x.PriceImpact
	}
	return 0
}

func (x *DryRunResult) GetEstimatedOutput() float64 {
	if x != nil {
		return x.EstimatedOutput
	}
	return 0
}

func (x *DryRunResult) GetIsSafe() bool {
	if x != nil {
		return x.IsSafe
	}
	return false
}

func (x *DryRunResult) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type SwapResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash         string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ExecutedPrice  float64                `protobuf:"fixed64,3,opt,name=executed_price,json=executedPrice,proto3" json:"executed_price,omitempty"`
	ActualSlippage float64                `protobuf:"fixed64,4,opt,name=actual_slippage,json=actualSlippage,proto3" json:"actual_slippage,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SwapResult) Reset() {
	*x = SwapResult{}
	mi := &file_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapResult) ProtoMessage() {}

func (x *SwapResult) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapResult.ProtoReflect.Descriptor instead.
func (*SwapResult) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{3}
}

func (x *SwapResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwapResult) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SwapResult) GetExecutedPrice() float64 {
	if x != nil {
		return x.ExecutedPrice
	}
	return 0
}

func (x *SwapResult) GetActualSlippage() float64 {
	if x != nil {
		return x.ActualSlippage
	}
	return 0
}

func (x *SwapResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PortfolioState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalCapital     float64                `protobuf:"fixed64,1,opt,name=total_capital,json=totalCapital,proto3" json:"total_capital,omitempty"`
	AvailableCapital float64                `protobuf:"fixed64,2,opt,name=available_capital,json=availableCapital,proto3" json:"available_capital,omitempty"`
	Positions        []*Position            `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PortfolioState) Reset() {
	*x = PortfolioState{}
	mi := &file_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioState) ProtoMessage() {}

func (x *PortfolioState) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioState.ProtoReflect.Descriptor instead.
func (*PortfolioState) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{4}
}

func (x *PortfolioState) GetTotalCapital() float64 {
	if x != nil {
		return x.TotalCapital
	}
	return 0
}

func (x *PortfolioState) GetAvailableCapital() float64 {
	if x != nil {
		return x.AvailableCapital
	}
	return 0
}

func (x *PortfolioState) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Size          float64                `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	EntryPrice    float64                `protobuf:"fixed64,3,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	UnrealizedPnl float64                `protobuf:"fixed64,5,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{5}
}

func (x *Position) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Position) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Position) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *Position) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Position) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

type LiquidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LiquidateAll  bool                   `protobuf:"varint,1,opt,name=liquidate_all,json=liquidateAll,proto3" json:"liquidate_all,omitempty"`
	Ticker        string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiquidateRequest) Reset() {
	*x = LiquidateRequest{}
	mi := &file_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiquidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiquidateRequest) ProtoMessage() {}

func (x *LiquidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiquidateRequest.ProtoReflect.Descriptor instead.
func (*LiquidateRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{6}
}

func (x *LiquidateRequest) GetLiquidateAll() bool {
	if x != nil {
		return x.LiquidateAll
	}
	return false
}

func (x *LiquidateRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type LiquidateResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PositionsClosed int32                  `protobuf:"varint,2,opt,name=positions_closed,json=positionsClosed,proto3" json:"positions_closed,omitempty"`
	TotalPnl        float64                `protobuf:"fixed64,3,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LiquidateResult) Reset() {
	*x = LiquidateResult{}
	mi := &file_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiquidateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiquidateResult) ProtoMessage() {}

func (x *LiquidateResult) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiquidateResult.ProtoReflect.Descriptor instead.
func (*LiquidateResult) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{7}
}

func (x *LiquidateResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LiquidateResult) GetPositionsClosed() int32 {
	if x != nil {
		return x.PositionsClosed
	}
	return 0
}

func (x *LiquidateResult) GetTotalPnl() float64 {
	if x != nil {
		return x.TotalPnl
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_execution_proto protoreflect.FileDescriptor

const file_execution_proto_rawDesc = "" +
	"\n" +
	"\x0fexecution.proto\x12\texecution\"\a\n" +
	"\x05Empty\"u\n" +
	"\vSwapRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x19\n" +
	"\bsize_usd\x18\x02 \x01(\x01R\asizeUsd\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x17\n" +
	"\ais_sell\x18\x04 \x01(\bR\x06isSell\"\xcf\x01\n" +
	"\fDryRunResult\x12-\n" +
	"\x12estimated_slippage\x18\x01 \x01(\x01R\x11estimatedSlippage\x12!\n" +
	"\fprice_impact\x18\x02 \x01(\x01R\vpriceImpact\x12)\n" +
	"\x10estimated_output\x18\x03 \x01(\x01R\x0festimatedOutput\x12\x17\n" +
	"\ais_safe\x18\x04 \x01(\bR\x06isSafe\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\"\xb4\x01\n" +
	"\n" +
	"SwapResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12%\n" +
	"\x0eexecuted_price\x18\x03 \x01(\x01R\rexecutedPrice\x12'\n" +
	"\x0factual_slippage\x18\x04 \x01(\x01R\x0eactualSlippage\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x95\x01\n" +
	"\x0ePortfolioState\x12#\n" +
	"\rtotal_capital\x18\x01 \x01(\x01R\ftotalCapital\x12+\n" +
	"\x11available_capital\x18\x02 \x01(\x01R\x10availableCapital\x121\n" +
	"\tpositions\x18\x03 \x03(\v2\x13.execution.PositionR\tpositions\"\xa3\x01\n" +
	"\bPosition\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x01R\x04size\x12\x1f\n" +
	"\ventry_price\x18\x03 \x01(\x01R\n" +
	"entryPrice\x12#\n" +
	"\rcurrent_price\x18\x04 \x01(\x01R\fcurrentPrice\x12%\n" +
	"\x0eunrealized_pnl\x18\x05 \x01(\x01R\runrealizedPnl\"O\n" +
	"\x10LiquidateRequest\x12#\n" +
	"\rliquidate_all\x18\x01 \x01(\bR\fliquidateAll\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\"s\n" +
	"\x0fLiquidateResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10positions_closed\x18\x02 \x01(\x05R\x0fpositionsClosed\x12\x1b\n" +
	"\ttotal_pnl\x18\x03 \x01(\x01R\btotalPnl\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xcd\x02\n" +
	"\x0fExecutionEngine\x12=\n" +
	"\n" +
	"DryRunSwap\x12\x16.execution.SwapRequest\x1a\x17.execution.DryRunResult\x12<\n" +
	"\vExecuteSwap\x12\x16.execution.SwapRequest\x1a\x15.execution.SwapResult\x12;\n" +
	"\fGetPortfolio\x12\x10.execution.Empty\x1a\x19.execution.PortfolioState\x12D\n" +
	"\tLiquidate\x12\x1b.execution.LiquidateRequest\x1a\x1a.execution.LiquidateResult\x12:\n" +
	"\vHealthCheck\x12\x10.execution.Empty\x1a\x19.execution.HealthResponseB\tZ\a./protob\x06proto3"

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData []byte
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)))
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_execution_proto_goTypes = []any{
	(*Empty)(nil),            // 0: execution.Empty
	(*SwapRequest)(nil),      // 1: execution.SwapRequest
	(*DryRunResult)(nil),     // 2: execution.DryRunResult
	(*SwapResult)(nil),       // 3: execution.SwapResult
	(*PortfolioState)(nil),   // 4: execution.PortfolioState
	(*Position)(nil),         // 5: execution.Position
	(*LiquidateRequest)(nil), // 6: execution.LiquidateRequest
	(*LiquidateResult)(nil),  // 7: execution.LiquidateResult
	(*HealthResponse)(nil),   // 8: execution.HealthResponse
}
var file_execution_proto_depIdxs = []int32{
	5, // 0: execution.PortfolioState.positions:type_name -> execution.Position
	1, // 1: execution.ExecutionEngine.DryRunSwap:input_type -> execution.SwapRequest
	1, // 2: execution.ExecutionEngine.ExecuteSwap:input_type -> execution.SwapRequest
	0, // 3: execution.ExecutionEngine.GetPortfolio:input_type -> execution.Empty
	6, // 4: execution.ExecutionEngine.Liquidate:input_type -> execution.LiquidateRequest
	0, // 5: execution.ExecutionEngine.HealthCheck:input_type -> execution.Empty
	2, // 6: execution.ExecutionEngine.DryRunSwap:output_type -> execution.DryRunResult
	3, // 7: execution.ExecutionEngine.ExecuteSwap:output_type -> execution.SwapResult
	4, // 8: execution.ExecutionEngine.GetPortfolio:output_type -> execution.PortfolioState
	7, // 9: execution.ExecutionEngine.Liquidate:output_type -> execution.LiquidateResult
	8, // 10: execution.ExecutionEngine.HealthCheck:output_type -> execution.HealthResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
