// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.0
// source: execution.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionEngine_DryRunSwap_FullMethodName   = "/execution.ExecutionEngine/DryRunSwap"
	ExecutionEngine_ExecuteSwap_FullMethodName  = "/execution.ExecutionEngine/ExecuteSwap"
	ExecutionEngine_GetPortfolio_FullMethodName = "/execution.ExecutionEngine/GetPortfolio"
	ExecutionEngine_Liquidate_FullMethodName    = "/execution.ExecutionEngine/Liquidate"
	ExecutionEngine_HealthCheck_FullMethodName  = "/execution.ExecutionEngine/HealthCheck"
)

// ExecutionEngineClient is the client API for ExecutionEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionEngineClient interface {
	DryRunSwap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*DryRunResult, error)
	ExecuteSwap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapResult, error)
	GetPortfolio(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PortfolioState, error)
	Liquidate(ctx context.Context, in *LiquidateRequest, opts ...grpc.CallOption) (*LiquidateResult, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type executionEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionEngineClient(cc grpc.ClientConnInterface) ExecutionEngineClient {
	return &executionEngineClient{cc}
}

func (c *executionEngineClient) DryRunSwap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*DryRunResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DryRunResult)
	err := c.cc.Invoke(ctx, ExecutionEngine_DryRunSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionEngineClient) ExecuteSwap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapResult)
	err := c.cc.Invoke(ctx, ExecutionEngine_ExecuteSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionEngineClient) GetPortfolio(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PortfolioState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioState)
	err := c.cc.Invoke(ctx, ExecutionEngine_GetPortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionEngineClient) Liquidate(ctx context.Context, in *LiquidateRequest, opts ...grpc.CallOption) (*LiquidateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LiquidateResult)
	err := c.cc.Invoke(ctx, ExecutionEngine_Liquidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionEngineClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ExecutionEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionEngineServer is the server API for ExecutionEngine service.
// All implementations must embed UnimplementedExecutionEngineServer
// for forward compatibility.
type ExecutionEngineServer interface {
	DryRunSwap(context.Context, *SwapRequest) (*DryRunResult, error)
	ExecuteSwap(context.Context, *SwapRequest) (*SwapResult, error)
	GetPortfolio(context.Context, *Empty) (*PortfolioState, error)
	Liquidate(context.Context, *LiquidateRequest) (*LiquidateResult, error)
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedExecutionEngineServer()
}

// UnimplementedExecutionEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionEngineServer struct{}

func (UnimplementedExecutionEngineServer) DryRunSwap(context.Context, *SwapRequest) (*DryRunResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRunSwap not implemented")
}
func (UnimplementedExecutionEngineServer) ExecuteSwap(context.Context, *SwapRequest) (*SwapResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSwap not implemented")
}
func (UnimplementedExecutionEngineServer) GetPortfolio(context.Context, *Empty) (*PortfolioState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortfolio not implemented")
}
func (UnimplementedExecutionEngineServer) Liquidate(context.Context, *LiquidateRequest) (*LiquidateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Liquidate not implemented")
}
func (UnimplementedExecutionEngineServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedExecutionEngineServer) mustEmbedUnimplementedExecutionEngineServer() {}
func (UnimplementedExecutionEngineServer) testEmbeddedByValue()                         {}

// UnsafeExecutionEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionEngineServer will
// result in compilation errors.
type UnsafeExecutionEngineServer interface {
	mustEmbedUnimplementedExecutionEngineServer()
}

func RegisterExecutionEngineServer(s grpc.ServiceRegistrar, srv ExecutionEngineServer) {
	// If the following call panics, it indicates UnimplementedExecutionEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionEngine_ServiceDesc, srv)
}

func _ExecutionEngine_DryRunSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionEngineServer).DryRunSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionEngine_DryRunSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionEngineServer).DryRunSwap(ctx, req.(*SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionEngine_ExecuteSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionEngineServer).ExecuteSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionEngine_ExecuteSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionEngineServer).ExecuteSwap(ctx, req.(*SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionEngine_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionEngineServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionEngine_GetPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionEngineServer).GetPortfolio(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionEngine_Liquidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiquidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionEngineServer).Liquidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionEngine_Liquidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionEngineServer).Liquidate(ctx, req.(*LiquidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionEngineServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionEngine_ServiceDesc is the grpc.ServiceDesc for ExecutionEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.ExecutionEngine",
	HandlerType: (*ExecutionEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DryRunSwap",
			Handler:    _ExecutionEngine_DryRunSwap_Handler,
		},
		{
			MethodName: "ExecuteSwap",
			Handler:    _ExecutionEngine_ExecuteSwap_Handler,
		},
		{
			MethodName: "GetPortfolio",
			Handler:    _ExecutionEngine_GetPortfolio_Handler,
		},
		{
			MethodName: "Liquidate",
			Handler:    _ExecutionEngine_Liquidate_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ExecutionEngine_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "execution.proto",
}
