# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import execution_pb2 as execution__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutionEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DryRunSwap = channel.unary_unary(
                '/execution.ExecutionEngine/DryRunSwap',
                request_serializer=execution__pb2.SwapRequest.SerializeToString,
                response_deserializer=execution__pb2.DryRunResult.FromString,
                _registered_method=True)
        self.ExecuteSwap = channel.unary_unary(
                '/execution.ExecutionEngine/ExecuteSwap',
                request_serializer=execution__pb2.SwapRequest.SerializeToString,
                response_deserializer=execution__pb2.SwapResult.FromString,
                _registered_method=True)
        self.GetPortfolio = channel.unary_unary(
                '/execution.ExecutionEngine/GetPortfolio',
                request_serializer=execution__pb2.Empty.SerializeToString,
                response_deserializer=execution__pb2.PortfolioState.FromString,
                _registered_method=True)
        self.Liquidate = channel.unary_unary(
                '/execution.ExecutionEngine/Liquidate',
                request_serializer=execution__pb2.LiquidateRequest.SerializeToString,
                response_deserializer=execution__pb2.LiquidateResult.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/execution.ExecutionEngine/HealthCheck',
                request_serializer=execution__pb2.Empty.SerializeToString,
                response_deserializer=execution__pb2.HealthResponse.FromString,
                _registered_method=True)


class ExecutionEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DryRunSwap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSwap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Liquidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DryRunSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.DryRunSwap,
                    request_deserializer=execution__pb2.SwapRequest.FromString,
                    response_serializer=execution__pb2.DryRunResult.SerializeToString,
            ),
            'ExecuteSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSwap,
                    request_deserializer=execution__pb2.SwapRequest.FromString,
                    response_serializer=execution__pb2.SwapResult.SerializeToString,
            ),
            'GetPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolio,
                    request_deserializer=execution__pb2.Empty.FromString,
                    response_serializer=execution__pb2.PortfolioState.SerializeToString,
            ),
            'Liquidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Liquidate,
                    request_deserializer=execution__pb2.LiquidateRequest.FromString,
                    response_serializer=execution__pb2.LiquidateResult.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=execution__pb2.Empty.FromString,
                    response_serializer=execution__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'execution.ExecutionEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('execution.ExecutionEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DryRunSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.ExecutionEngine/DryRunSwap',
            execution__pb2.SwapRequest.SerializeToString,
            execution__pb2.DryRunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.ExecutionEngine/ExecuteSwap',
            execution__pb2.SwapRequest.SerializeToString,
            execution__pb2.SwapResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.ExecutionEngine/GetPortfolio',
            execution__pb2.Empty.SerializeToString,
            execution__pb2.PortfolioState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Liquidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.ExecutionEngine/Liquidate',
            execution__pb2.LiquidateRequest.SerializeToString,
            execution__pb2.LiquidateResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.ExecutionEngine/HealthCheck',
            execution__pb2.Empty.SerializeToString,
            execution__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
